export const surprisePrompts = [
  "A futuristic city floating in the sky during sunset",
  "A cat wearing a spacesuit floating in space",
  "A cyberpunk samurai in a neon-lit alley",
  "A peaceful village on a giant lily pad",
  "An astronaut exploring an alien jungle",
  "A robot painting a portrait of a human",
  "A dragon made of clouds flying over mountains",
  "A surreal dreamscape with melting clocks and floating islands",
  "A magical forest with glowing trees and fairies",
  "A retro 80s-style arcade on Mars",
  "A steampunk owl flying over a foggy London",
  "A pirate ship sailing through the desert",
  "A penguin detective solving a mystery in New York",
  "A crystal castle floating in the Arctic",
  "A giant whale flying through a starry sky",
  "A ballerina dancing in zero gravity",
  "An underwater city with bioluminescent creatures",
  "A mystical portal in the middle of a sunflower field",
  "A superhero made entirely of books",
  "A dog astronaut on the Moon holding a flag",
  "A floating tea party in a bubble over the ocean",
  "A cactus playing the guitar in the desert",
  "A space train traveling between galaxies",
  "A neon jellyfish parade in a futuristic city",
  "A surreal staircase that leads into the sky",
  "A warrior riding a flaming horse through a blizzard",
  "A futuristic café run by robots",
  "A moon made of cheese being eaten by a mouse spaceship",
  "A glitchy pixel art dragon fighting a knight",
  "A flying bicycle over the clouds at twilight",
  "A sushi platter designed like a fantasy kingdom",
  "A galaxy growing inside a terrarium",
  "A time traveler meeting dinosaurs in neon suits",
  "A haunted house made of candy and chocolate",
  "A jazz band playing on a boat in space",
  "A teddy bear knight defending a kingdom of toys",
  "A jellybean planet surrounded by candy comets",
  "A renaissance-style portrait of an alien queen",
  "A desert oasis shaped like a giant eye",
  "A rainbow waterfall in a crystal canyon",
  "A wolf howling at a binary code moon",
  "A robot and a bird sharing a moment on a rooftop",
  "A skyscraper shaped like a giant tree",
  "A wizard casting spells through a smartphone",
  "A chess match between a fox and an owl",
  "A festival in a village inside a teacup",
  "A street food market on Saturn’s rings",
  "A volcano erupting confetti instead of lava",
  "A lone samurai meditating under cherry blossoms in space",
  "A house flying with balloons and rocket boosters"
];
